@startjson
{
  "protokollnavn": "no.ks.fiks.matrikkelfoering",
  "navn": "tiltaktype",
  "versjon": "v2",
  "definisjon": "Kilde: https://register.geonorge.no/kodelister/byggesoknad/tiltaktype?sorting=codevalue",
  "kodeliste": [
    {
      "kodeverdi" : "anleggseiendom",
      "kodebeskrivelse" : "Delesak - fradeling av eiendom til anleggsformål - anleggstomt"
    },
    {
      "kodeverdi" : "antenneover5m",
      "kodebeskrivelse" : "Antennesystem med høyde over 5m"
    },
    {
      "kodeverdi" : "arealoverføring",
      "kodebeskrivelse" : "Delesak - overføring av areal fra en eiendom til en annen"
    },
    {
      "kodeverdi" : "berekonstruksjoner",
      "kodebeskrivelse" : "Endring av bærekonstruksjon i eksisterende bygning - ikke synlig utvendig"
    },
    {
      "kodeverdi" : "boligoppdeling",
      "kodebeskrivelse" : "Denne skal benyttes dersom en leilighet skal deles opp i flere boenheter"
    },
    {
      "kodeverdi" : "boligsammenslaing",
      "kodebeskrivelse" : "Denne skal benyttes dersom to eller flere leiligheter skal slås sammen til en. For eksempel omgjøring av tomannsbolig til enebolig"
    },
    {
      "kodeverdi" : "brannskille",
      "kodebeskrivelse" : "Endring av brannskille i eksisterende bygning - ikke synlig utvendig"
    },
    {
      "kodeverdi" : "bruksendring",
      "kodebeskrivelse" : "Kun endring av bruk - ingen bygningsmessige endringer"
    },
    {
      "kodeverdi" : "bruksendringhoveddel",
      "kodebeskrivelse" : "Kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "driftsbygningendringover1000m2",
      "kodebeskrivelse" : " 1000m2 (BRA)Endringer, tilbygg eller påbygg til eksisterende driftsbygning som er over 1.000m2"
    },
    {
      "kodeverdi" : "driftsbygningendringunder1000m2",
      "kodebeskrivelse" : "Endringer, tilbygg eller påbygg til eksisterende driftsbygning hvor ferdig bygg holder seg under 1.000m2 - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "driftsbygningtilbyggover1000m2",
      "kodebeskrivelse" : "Tilbygg til eksisterende driftsbygning i landbruket hvor bygningen til sammen får et bruksareal som er større enn 1.000m2"
    },
    {
      "kodeverdi" : "driftsbygningtilbyggunder1000m2",
      "kodebeskrivelse" : "Tilbygg til eksisterende driftsbygning i landbruket hvor bygningen til sammen får et bruksareal som er mindre enn 1.000m2 - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "endringanlegg",
      "kodebeskrivelse" : "Endring av eksisterende bygning, hvor ingen andre tiltakstyper passer"
    },
    {
      "kodeverdi" : "endringbyggannet",
      "kodebeskrivelse" : "Denne skal benyttes dersom en leilighet skal deles opp i flere boenheter"
    },
    {
      "kodeverdi" : "endringdrift",
      "kodebeskrivelse" : "Vesentlig endring av drift uten at endringen medfører bruksendring"
    },
    {
      "kodeverdi" : "fasade",
      "kodebeskrivelse" : "Endring av en eller flere fasader på eksisterende bygning"
    },
    {
      "kodeverdi" : "festegrunn",
      "kodebeskrivelse" : "Delesak - fradeling av festetomter"
    },
    {
      "kodeverdi" : "fundamenter",
      "kodebeskrivelse" : "Endring av fundamenter i eksisterende bygning - ikke synlig utvendig"
    },
    {
      "kodeverdi" : "grunneiendom",
      "kodebeskrivelse" : "Delesak - fradeling av nye tomter"
    },
    {
      "kodeverdi" : "hovedombygging",
      "kodebeskrivelse" : "Gyldig fra 23. februar 2023. Ved en hovedombygging er arbeidene så omfattende at hele bygningen i det vesentlige blir fornyet"
    },
    {
      "kodeverdi" : "innhegning",
      "kodebeskrivelse" : "Gjerde - det er kun gjerde mot vei som er søknadspliktig - gjerde som er lavere enn 1,5m er unntatt søknadsplikt med mindre det hindrer sikten i frisiktsone mot vei"
    },
    {
      "kodeverdi" : "installasjonernyttanlegg",
      "kodebeskrivelse" : "Dette er tekniske installasjoner som er knyttet til drift av bygningen (heis, ventilasjon, sprinkling osv.)"
    },
    {
      "kodeverdi" : "installasjonerreparasjon",
      "kodebeskrivelse" : "Dette er tekniske installasjoner som er knyttet til drift av bygningen (heis, ventilasjon, sprinkling osv.)"
    },
    {
      "kodeverdi" : "installasjonibygg",
      "kodebeskrivelse" : "Dette er tekniske installasjoner som er knyttet til drift av bygningen (heis, ventilasjon, sprinkling osv.)"
    },
    {
      "kodeverdi" : "lydskille",
      "kodebeskrivelse" : "Endring av lydskille i eksisterende bygning - ikke synlig utvendig"
    },
    {
      "kodeverdi" : "mikrohus",
      "kodebeskrivelse" : "Frittliggende boligbygning inntil 30 m2 BRA med én boenhet i én etasje uten kjeller som ikke på noe punkt overstiger en høyde på 4,5 m over bakken. Tiltakstypen blir gyldig fra 1. juli 2023."
    },
    {
      "kodeverdi" : "nyttanlegg",
      "kodebeskrivelse" : "Anlegg er fysiske og selvstendige tiltak som ikke er bygning (støttemurer, svømmebassing, vei, brygger, terrengendringer osv.)"
    },
    {
      "kodeverdi" : "nyttbyggboligformal",
      "kodebeskrivelse" : "Denne tiltakstypen skal benyttes ved søknad om nye boliger eller nye fritidsboliger"
    },
    {
      "kodeverdi" : "nyttbyggdriftsbygningover1000m2",
      "kodebeskrivelse" : "Nye driftsbygninger i landbruket hvor samlet BRA eller BYA er over 1.000 m2"
    },
    {
      "kodeverdi" : "nyttbyggdriftsbygningunder1000m2",
      "kodebeskrivelse" : "Nye driftsbygninger i landbruket hvor samlet BRA eller BYA er under 1.000 m2 - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "nyttbyggover70m2",
      "kodebeskrivelse" : "Alle typer bygg over 70 m2 unntatt boliger eller fritidsboliger"
    },
    {
      "kodeverdi" : "nyttbyggunder70m2",
      "kodebeskrivelse" : "Alle typer bygg under 70 m2 unntatt boliger eller fritidsboliger - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "pabygg",
      "kodebeskrivelse" : "Påbygg på eksisterende bygning - påbygg 'hviler' på eksisterende konstruksjoner, mens tilbygg har nye egne fundamenter"
    },
    {
      "kodeverdi" : "parkeringsplass",
      "kodebeskrivelse" : "Anlegg - parkeringsplass"
    },
    {
      "kodeverdi" : "plasseringmidlertidig",
      "kodebeskrivelse" : "Tiltak som ikke skal stå i mer enn 2 år - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "rivinganlegg",
      "kodebeskrivelse" : "Anlegg er fysiske og selvstendige tiltak som ikke er bygning (støttemurer, svømmebassing, vei, brygger, terrengendringer osv.)"
    },
    {
      "kodeverdi" : "rivingbygningunder70m2",
      "kodebeskrivelse" : "Riving av en hel bygning som ikke er større enn 70m2 - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "rivingdriftsbygninginntill1000m2",
      "kodebeskrivelse" : "Riving av en hel driftsbygning som ikke er større enn 1.000m2 - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "rivinghelebygg",
      "kodebeskrivelse" : "Riving av hele bygg som er større enn 70m2, eller driftsbygning større enn 1000 m2"
    },
    {
      "kodeverdi" : "rivingtilbygginntil50m2",
      "kodebeskrivelse" : "Riving av et tilbygg som ikke er større enn 50m2 - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "skiltreklamefasadeliten",
      "kodebeskrivelse" : "Mindre skilt montert på en fasade - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "skiltreklamefasadestor",
      "kodebeskrivelse" : "Større skilt montert på en fasade"
    },
    {
      "kodeverdi" : "skiltreklamefrittstaendeliten",
      "kodebeskrivelse" : "Mindre frittstående skilt - kan bruke søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "skiltreklamefrittstaendestor",
      "kodebeskrivelse" : "Større frittstående skilt"
    },
    {
      "kodeverdi" : "terrenginngrep",
      "kodebeskrivelse" : "Anlegg - vesentlig terrenginngrep - SAK10 § 4-1 definerer unntak fra søknadsplikt"
    },
    {
      "kodeverdi" : "tilbyggover50m2",
      "kodebeskrivelse" : "Tilbygg til eksisterende bygning - tilbygg har nye egne fundamenter"
    },
    {
      "kodeverdi" : "tilbyggunder50m2",
      "kodebeskrivelse" : "Tilbygg til eksisterende bygning - tilbygg har nye egne fundamenter. For tilbygg mindre enn 50m2, kan det brukes søknad uten ansvarsrett"
    },
    {
      "kodeverdi" : "underbygg",
      "kodebeskrivelse" : "Underbygging av eksisterende bygning - for eksempel utgraving og utbygging av kjeller"
    },
    {
      "kodeverdi" : "utvendigeinstallasjoner",
      "kodebeskrivelse" : "Dette er tekniske installasjoner som er knyttet til drift av bygningen (ventilasjon, vinduspusseheiser osv.)"
    },
    {
      "kodeverdi" : "vatrom",
      "kodebeskrivelse" : "Endring av våtrom i eksisterende bygning"
    },
    {
      "kodeverdi" : "veg",
      "kodebeskrivelse" : "Anlegg - bygging av ny vei"
    }
  ]
}
@endjson