@startuml

class Kvittering {
    +status : Status
    +melding : string
    +tiltakid : string
    +byggIdent : string
}
class KvitteringMatrikkel {
    +saksnummer : Saksnummer
    +status : OverordnetStatus
    +melding : string
    +kvitteringer : Kvittering[]
}
enum OverordnetStatus {
    ok = ok
    feilet = feilet
}
class Saksnummer {
    +saksaar : integer
    +sakssekvensnummer : integer
}
enum Status {
    velykket = velykket
    feilet = feilet
    skalIkkeMatrikkelfoeres = skalIkkeMatrikkelfoeres
}

@enduml
