@startjson
{
  "protokollnavn": "no.ks.fiks.matrikkelfoering",
  "versjon": "v2",
  "meldingstyper": [
    {
      "id": "no.ks.fiks.matrikkelfoering.v2.grunnlag",
      "beskrivelse": "",
      "harPayload": true,
      "payloadFilnavn": ["byggesak.xml", "index.json"],
      "kanSvareMed": ["no.ks.fiks.matrikkelfoering.v2.mottatt", "no.ks.fiks.matrikkelfoering.v2.kvittering", "no.ks.fiks.matrikkelfoering.v2.feilmelding.ugyldigforespoersel", "no.ks.fiks.matrikkelfoering.v2.feilmelding.serverfeil"]
    },
    {
      "id": "no.ks.fiks.matrikkelfoering.v2.mottatt",
      "beskrivelse": "",
      "harPayload": false,
      "erSvarPaa": ["no.ks.fiks.matrikkelfoering.v2.grunnlag"]
    },
    {
      "id": "no.ks.fiks.matrikkelfoering.v2.kvittering",
      "beskrivelse": "",
      "harPayload": true,
      "payloadFilnavn": "kvittering.xml",
      "erSvarPaa": ["no.ks.fiks.matrikkelfoering.v2.grunnlag"]
    },
    {
      "id": "no.ks.fiks.matrikkelfoering.v2.status",
      "beskrivelse": "Forespørsel om status på en sak",
      "harPayload": true,
      "payloadFilnavn": "status.xml",
      "kanSvareMed": ["no.ks.fiks.matrikkelfoering.v2.statussvar", "no.ks.fiks.plan.v2.feilmelding.ugyldigforespoersel", "no.ks.fiks.plan.v2.feilmelding.serverfeil"]
    },
    {
      "id": "no.ks.fiks.matrikkelfoering.v2.statussvar",
      "beskrivelse": "",
      "harPayload": true,
      "payloadFilnavn": "statussvar.xml",
      "erSvarPaa": ["no.ks.fiks.matrikkelfoering.v2.status"]
    },
    {
      "id": "no.ks.fiks.matrikkelfoering.v2.feilmelding.ugyldigforespoersel",
      "beskrivelse": "",
      "harPayload": true,
      "payloadFilnavn": "feilmelding.xml",
      "erSvarPaa": ["no.ks.fiks.matrikkelfoering.v2.grunnlag", "no.ks.fiks.matrikkelfoering.v2.status"]
    },
    {
      "id": "no.ks.fiks.matrikkelfoering.v2.feilmelding.serverfeil",
      "beskrivelse": "",
      "harPayload": true,
      "payloadFilnavn": "feilmelding.xml",
      "erSvarPaa": ["no.ks.fiks.matrikkelfoering.v2.grunnlag", "no.ks.fiks.matrikkelfoering.v2.status"]
    }
  ]
}
@endjson